default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  database: <%= ENV['DB_NAME'] %>
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'adnexus_dev' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] || 'adnexus' %>
  password: <%= ENV['DB_PASSWORD'] || 'adnexus' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'adnexus_test' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
